# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FirebaseDemo2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseDemo2
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end
